POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "alessa",
  "password": "alessa"
}

###

GET http://localhost:8080/api/admin/me

###

GET http://localhost:8080/api/admin/images

###

POST http://localhost:8080/api/logout
Content-Type: application/json

###

GET http://localhost:8080/api/recipes/1/explore