spring.jpa.hibernate.ddl-auto=validate

# Generate OpenAPI description on each startup
# see: OpenApiDocGenerator.java
generate-open-api-doc-on-startup.enabled=true

# Sortieren der Properties von Components in der yaml-datei
# um die Ausgabe stabil zu halten
springdoc.writer-with-order-by-keys=true

#spring.docker.compose.file=${user.dir}/docker-compose-development.yaml

recipify.web.images-dir=file://${user.dir}/web-root/images/
recipify.web.upload-dir=file://${user.dir}/web-root/images/upload/
recipify.web.upload-url-path=/images/upload/

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

